       os: osx
       osx_image: xcode10.1
       node_js: 10
       cache:
         yarn: true
         directories:
           - node_modules
       before_install:
           - curl -o- -L https://yarnpkg.com/install.sh | bash
           - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"    
           - gem install cocoapods --pre
       install:           
          - yarn global add cavy-cli
          - yarn global add react-native-cli
          - yarn install 
       script:
         - react-native start --reset-cache &
         - cavy run-ios
        